package com.nkhoang.common.util.parser;

/** Listens to parse events from a LineParser */
public interface ParseListener {

	/** Called once when parsing starts */
	void startData();

	/**
	 * Called for each token parsed.  Note that a CharSequence is NOT a String.
	 * The value may change out from under you if you hold on to it after this
	 * method returns.  If you need to hold on to the value, you probably
	 * want to copy it into a String.
	 */
	void nextToken(CharSequence token) throws LineParseException;

	/** Resets line tokens. This method should be called before parsing next line. */
	void initTokens();

	/**
	 * Called at the end of each line
	 *
	 * @return True to continue parsing, false to stop
	 */
	boolean endLine() throws LineParseException;

	/**
	 * Called at the end of each line.
	 *
	 * @param lineNumber Line number of the line being processed
	 *
	 * @return True to continue parsing, false to stop
	 *
	 * @throws LineParseException
	 */
	boolean endLine(int lineNumber) throws LineParseException;

	/**
	 * Should be called whenever a parse error occurs.
	 *
	 * @param lineNumber Line number of the error line
	 */
	void addErrorLine(int lineNumber);

	/**
	 * Called whenever a warning is generated by the parser, between startData
	 * and endData.
	 */
	void addWarning(int lineNumber, String msg) throws LineParseException;

	/** Called once at the end of the parsing */
	void endData();

}
